---
# install the basic packages on Debian

- name: make sure aptitude is installed
  apt:
    name: aptitude
    state: latest

- name: update repo cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  changed_when: false

- name: install basic packages
  apt:
    name: "{{ debian_packages }}"
    state: latest
  check_mode: false

- name: install additional packages
  apt:
    name: "{{ debian_additional_packages }}"
    state: latest
  check_mode: false
