---
# install the basic packages onsl_debian

- name: make sure aptitude is installed
  apt:
    name: aptitude
    state: latest

- name: activate locales
  replace:
    path: /etc/locale.gen
    regexp: "# ({{ item }}\\.UTF-8.*)"
    replace: '\1'
  loop: "{{ sl_lx_locales }}"

- name: generate locales
  command: locale-gen

- name: update default locale
  command: "update-locale LANG={{ sl_lx_default_locale }}.UTF-8"

- name: update repo cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  changed_when: false

- name: install basic packages
  apt:
    name: "{{ sl_debian_packages }}"
    state: latest

- name: install additional packages
  apt:
    name: "{{ sl_debian_additional_packages }}"
    state: latest

- name: install Perl packages
  apt:
    name: "{{ sl_debian_perl_packages }}"
    state: latest

- name: install Perl modules from CPAN
  command: "cpanm {{ item }}"
  loop: "{{ sl_debian_perl_cpan }}"

- name: install additional Perl modules from CPAN
  command: "cpanm {{ item }}"
  loop: "{{ sl_debian_perl_additional_cpan }}"

- name: set time zone
  command: "timedatectl set-timezone {{ sl_lx_timezone }}"
