---
# install the basic packages on Debian

- name: make sure aptitude is installed
  apt:
    name: aptitude
    state: latest

- name: activate locale
  replace:
    path: /etc/locale.gen
    regexp: "# ({{ debian_locale }}\\.UTF-8.*)"
    replace: '\1'

- name: generate locales
  command: locale-gen

- name: update locale
  command: "update-locale LANG={{ default_locale }}.UTF-8"

- name: update repo cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  changed_when: false

- name: install basic packages
  apt:
    name: "{{ debian_packages }}"
    state: latest
  check_mode: false

- name: install additional packages
  apt:
    name: "{{ debian_additional_packages }}"
    state: latest
  check_mode: false

- name: set time zone
  command: "timedatectl set-timezone {{ sl_timezone }}"
