---
# install the basic packages on Debian

- name: Debian specifics
  set_fact:
    httpd_user: "{{ debian_vars.httpd_user }}"
    httpd_group: "{{ debian_vars.httpd_group }}"

- name: make sure aptitude is installed
  apt: name=aptitude state=latest

- name: update repo cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  changed_when: false

- name: install basic packages
  apt: name={{ item }} state=latest
  check_mode: no
  with_items: "{{ debian_packages }}"
