---

- name: clone from Github
  git:
    repo: "{{ git_source }}"
    version: "{{ git_branch }}"
    dest: "{{ httpd_path }}"
    accept_hostkey: yes

- name: copy config files
  template: src={{ item }} dest={{ httpd_path }}/{{ item }}
  with_items:
    - sql-ledger.conf
    - wlprinter.conf

- name: create directories
  file: dest={{ httpd_path }}/{{ item }} state=directory
  with_items:
    - spool
    - templates

- include: set_admin_pwd.yml
  when: sl_admin_pwd is defined

- name: change permissions
  file:
    dest: "{{ httpd_path }}/{{ item }}"
    owner: "{{ httpd_user }}"
    group: "{{ httpd_group }}"
    recurse: yes
  with_items:
    - css
    - spool
    - templates
    - users
