---

- name: install postgres
  apt: name={{ item }} state=latest
  with_items:
    - postgresql
    - postgresql-server-dev-{{ postgres_version }}
    - libdbi-perl

- name: install DBD::Pg
  command: cpanm DBD::Pg@{{ dbd_pg_version }}

- name: change permissions
  replace:
    dest: /etc/postgresql/{{ postgres_version }}/main/pg_hba.conf
    regexp: '(local.+all.+.all.+)peer'
    replace: '\1trust'
  notify: restart postgres
  
- name: check if sql-ledger user exists
  command: su postgres -c 'psql -c "select * from pg_user"' warn=no
  register: pg_user

- name: create user for sql-ledger
  command: su postgres -c 'createuser -d -R -S {{ postgres_user }}' warn=no
  when: pg_user.stdout.find("{{ postgres_user }}") == -1
