---

- name: install latex packages
  apt:
    name: "{{ sl_debian_latex_packages }}"
    state: latest

- name: install xelatex
  apt:
    name: texlive-xetex
    state: latest
  when: sl_latex_xelatex

- name: install pdftk
  apt:
    name: pdftk-java
    state: latest
  when: sl_latex_pdftk

- name: install texlive languages
  apt:
    name: "texlive-lang-{{ item }}"
    state: latest
  loop: "{{ sl_texlive_languages }}"
