---

- name: Debian specifics
  set_fact:
    httpd_user: "{{ debian_vars.httpd_user }}"
    httpd_group: "{{ debian_vars.httpd_group }}"

- name: clone from Github
  git:
    repo: "{{ sl_git_source }}"
    version: "{{ sl_git_branch }}"
    dest: "{{ sl_httpd_path }}"
    accept_hostkey: true

- name: create subdirectories
  file:
    dest: "{{ sl_httpd_path }}/{{ item }}"
    state: directory
  loop:
    - spool
    - templates

- include_tasks: set_admin_pwd.yml
  when: sl_admin_pwd is defined

- name: change permissions
  file:
    dest: "{{ sl_httpd_path }}/{{ item }}"
    owner: "{{ httpd_user }}"
    group: "{{ httpd_group }}"
    recurse: true
  loop:
    - css
    - images
    - spool
    - templates
    - users

- name: create gpg directory
  file:
    dest: "{{ sl_gpg_path }}"
    state: directory
    owner: "{{ httpd_user }}"
    group: "{{ httpd_group }}"
