---

- name: clone from Github
  git:
    repo: "{{ sl_git_source }}"
    version: "{{ sl_git_branch }}"
    dest: "{{ sl_httpd_path }}"
    accept_hostkey: true
  notify: run tests

- name: create subdirectories
  file:
    dest: "{{ sl_httpd_path }}/{{ item }}"
    state: directory
  loop:
    - spool
    - templates

- name: change permissions
  file:
    dest: "{{ sl_httpd_path }}/{{ item }}"
    owner: "{{ sl_httpd_user }}"
    group: "{{ sl_httpd_group }}"
    recurse: true
  loop:
    - css
    - images
    - spool
    - templates
    - users

- name: create gpg directory
  file:
    dest: "{{ sl_gpg_path }}"
    state: directory
    owner: "{{ sl_httpd_user }}"
    group: "{{ sl_httpd_group }}"
    mode: '0700'
