---
# set the password for admin.pl if sl_admin_pwd is defined

- name: encrypt password
  command: perl -e "print crypt '{{ sl_admin_pwd }}', 'root'"
  register: encrypted_pwd

- name: copy members file
  template: src=members dest={{ sl_httpd_path }}/users/members force=no

- name: update password
  replace:
    dest: "{{ sl_httpd_path }}/users/members"
    regexp: '(\[root login\]\npassword=).*'
    replace: '\1{{ encrypted_pwd.stdout }}'
  register: update_pwd

- name: remove config file
  file: dest="{{ sl_httpd_path }}/users/root login.conf" state=absent
  when: update_pwd|changed
