---
# set the password for admin.pl if sl_admin_pwd is defined

- name: encrypt password
  command: perl -e "print crypt '{{ sl_admin_pwd }}', 'root'"
  register: sl_encrypted_admin_pwd

- name: create members file
  template:
    src: members_yml.j2
    dest: "{{ sl_httpd_path }}/users/members.yml"
    force: false

- name: update password
  replace:
    dest: "{{ sl_httpd_path }}/users/members.yml"
    regexp: '(root login:\n  password:).*'
    replace: '\1 {{ sl_encrypted_admin_pwd.stdout }}'
  notify: update binary config
