---

- name: copy site config
  template:
    src: sql-ledger.httpd.conf
    dest: "/etc/apache2/sites-available/{{ sl_httpd_url }}.conf"
  notify:
    - reload apache2

- name: check if site is activated
  command: a2query -s {{ sl_httpd_url }}
  failed_when: false
  changed_when: false
  register: sitequery

- name: activate site
  command: a2ensite {{ sl_httpd_url }}
  when: sitequery.stdout.find('enabled') == -1
  notify:
    - reload apache2

- name: enable cgid module
  apache2_module: name=cgid state=present
  notify:
    - restart apache2
